name: Build and Distribute with Firebase

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git flutter-sdk && cd flutter-sdk && git fetch --all --tags && git checkout tags/2.6.0-0.0.pre && ./bin/flutter doctor && pwd
          
      - name: setup Firebase CLI
        run: |
          brew install firebase-cli && pwd
