name: dev_analysis

on:
  push:

    branches:
      - '*'

  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: macos-latest

    steps:
      - name: Get Flutter
        run: "git clone https://github.com/flutter/flutter.git"
      - name: Set flutter version and branch
        run: |
          - "git fetch origin tags/2.6.0-0.0.pre"
          - "git checkout tags/2.6.0-0.0.pre"
      - name: Add to path
        run: "export PATH=\"$PATH:`pwd`/flutter/bin\""
      - name: Initialize Flutter
        run: "flutter doctor"
