name: dev_analysis

on:
  push:

    branches:
      - '*'

  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: macos-latest

    steps:
      - name: Get Flutter
        run: "git clone https://github.com/flutter/flutter.git"
      - name: Fetch flutter version
        run: git fetch origin tags/2.6.0-0.0.pre
      - name: Checkout version
        run: git checkout tags/2.6.0-0.0.pre
      - name: Add flutter to path
        run: export PATH=\"$PATH:`pwd`/flutter/bin\"
      - name: Initialize Flutter
        run: flutter doctor
