name: dev_analysis

on:
  push:

    branches:
      - '*'

  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: macos-latest

    steps:
      - name: Setup Flutter
        run: ls && pwd && git clone https://github.com/flutter/flutter.git && cd flutter && git fetch origin tags/2.6.0-0.0.pre && git checkout tags/2.6.0-0.0.pre && export PATH="$PATH:`pwd`/bin && flutter doctor && pwd && ls"
      - name: Get project
        run: ls && pwd && git clone https://github.com/mludovico/flutter_ci_study.git project && pwd && ls
      - name: Analyze
        run: ls && pwd && cd project && ../flutter/bin/flutter analyze && pwd && ls
